# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RocketLang < Formula
  desc ""
  homepage "https://auch.cool/"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.23.0/rocket-lang_darwin_amd64_v0.23.0.tar.gz"
      sha256 "86bd598b368ab2960cc5a36c249707be437490e8d701585fc27198a1878df0d2"

      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.23.0/rocket-lang_darwin_arm64_v0.23.0.tar.gz"
      sha256 "949a8e4f77f4184736b83fe0b94916718863bac8e878d6b2f181da086c9ee3d1"

      def install
        bin.install "rocket-lang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.23.0/rocket-lang_linux_amd64_v0.23.0.tar.gz"
      sha256 "373362812f8abb24e6417a9a4302a370bbaee502abe40dd28ffdb9dbf8ed6ad5"
      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.23.0/rocket-lang_linux_arm_v0.23.0.tar.gz"
      sha256 "a5a59a66b696ec3acb6d33e643d675b617a87e30a61d594ade428ea0d140c2d3"
      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.23.0/rocket-lang_linux_arm64_v0.23.0.tar.gz"
      sha256 "50bdec73f397400bcbc5891c57a34c90ea8e512deb78b64183071ba084a380a9"
      def install
        bin.install "rocket-lang"
      end
    end
  end
end
