# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RocketLang < Formula
  desc ""
  homepage "https://auch.cool/"
  version "0.17.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.17.1/rocket-lang_darwin_amd64.tar.gz"
      sha256 "9ed2445f0f3b9478e51521ee9e1cf516354f99d161eb03e008c4b9bb07a9a445"

      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.17.1/rocket-lang_darwin_arm64.tar.gz"
      sha256 "272c70e4304cb113a0b7d432da17f941f7d6e3e73a53b1578e4cc449005c7d9e"

      def install
        bin.install "rocket-lang"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.17.1/rocket-lang_linux_arm64.tar.gz"
      sha256 "5a2bb14d874b7c58fd43859e709ff90b9fb176675708665db7b1e288a0d29517"

      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.17.1/rocket-lang_linux_arm.tar.gz"
      sha256 "305862a5afcd3751aca36376efbd2a3a7d73eecd11547185bbdb1aa4587aa19d"

      def install
        bin.install "rocket-lang"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.17.1/rocket-lang_linux_amd64.tar.gz"
      sha256 "04da3df8a9af8cf7fb0fcfc30bef4366a594182b6e92062f41802e38fc17e097"

      def install
        bin.install "rocket-lang"
      end
    end
  end
end
