# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RocketLang < Formula
  desc ""
  homepage "https://auch.cool/"
  version "0.9.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.9.6/rocket-lang_darwin_amd64.tar.gz"
      sha256 "efdaed91d980971d0509fe9aef5f0c5c7d8c5172ac7ea60376ac265c07198237"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Flipez/rocket-lang/releases/download/v0.9.6/rocket-lang_linux_amd64.tar.gz"
      sha256 "4407815cb3344e8a8829819b446142427b263c6df9311c271fdf559f32944965"
    end
  end

  def install
    bin.install "rocket-lang"
  end
end
